language: node_js
node_js:
  - '0.10'
	- '0.8'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-fixate-pw' ]; then cd .. && eval "mv $currentfolder generator-fixate-pw" && cd generator-fixate-pw; fi

